### ISSUE TITLE
Problem in spree 3.2.1

### ISSUE THREAD

**Issue by mikosh** [vinzloh/spree_product_hover_zoom#3]
Looks like spree_product_hover_zoom is not working in spree 3.2.1

Nothing happens on hover the product image.

drift and luminous are loaded.

**Comment by htorohn** [comment]
Hi mikosh, did you find a solution for this problem? I'm having the same issue.

**Comment by mikosh** [comment]
Unfortunately no, do you use spree 3.2.1?

**Comment by surajkincity** [comment]
same issue

**Comment by Gaurav2728** [comment]
Sorry folks due to time issue and traveling I can't look it now but we try to sort out the problem.
PR welcome if you want to work on that.

**Comment by untitled655321** [comment]
Same problem.

**Comment by ShuaibMalik1** [comment]
Same issue.

**Comment by vinzloh** [comment]
#4

**Comment by ShuaibMalik1** [comment]
the issue has been fixed in latest commit.
